CXX = g++

default: or and xor not

or: or.c
	$(CXX) or.c -o or

and: and.c
	$(CXX) and.c -o and 

xor: xor.c
	$(CXX) xor.c -o xor 

not: not.c
	$(CXX) not.c -o not 

clean:
	rm or and xor not

all: clean or and xor not
